export ALPHAVANTAGE_API_KEY = "JD2BSL1QF13GVKR7"
echo $ALPHAVANTAGE_API_KEY;
export ALPACA_PAPER_ENDPOINT = "https://paper-api.alpaca.markets"
echo $ALPACA_PAPER_ENDPOINT;
export ALPACA_API_KEY = "PKK6EBD71EQANNWEN2IX"
echo $ALPACA_API_KEY;
export ALPACA_SECRET_KEY = "n4YMLwuOuasolZemY5o4etUtLpeKKRb79uASh9lW"
echo $ALPACA_SECRET_KEY;
jupyter-lab.;